#!/bin/bash

source "${BASH_SOURCE%/*}/../../lib/scenario.bash" || exit 1

kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/zones-add-radius.xsl" -s 'additional-radius-miles=0.1' "$kmlpipe_script_dir/input.kml" > "$kmlpipe_tmpdir/output.kml"
kmlpipe_validate_kml "$kmlpipe_tmpdir/output.kml"
kmlpipe_check_golden_xml "$kmlpipe_script_dir/output.kml" < "$kmlpipe_tmpdir/output.kml"
