# See https://docs.travis-ci.com/

dist: xenial
language: minimal
install:
  # Add a more modern version of Ubuntu so that we can get bash 4.4
  - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ bionic main'
  - sudo apt-get -y update
  - sudo apt-get install bash curl jq xmlstarlet
script:
  - test/run-scenarios
