#!/bin/bash

source "${BASH_SOURCE%/*}/../../lib/scenario.bash" || exit 1

KMLPIPE_FETCH_REPLAY_DIR="$kmlpipe_script_dir/replay" "$kmlpipe_dir/edechamps-home-hunt/widen" \
	--input-listings-file "$kmlpipe_script_dir/listings.kml" --input-workplace-file "$kmlpipe_script_dir/workplace.kml" --input-supermarkets-file "$kmlpipe_script_dir/supermarkets.kml" --input-hyperoptic-file "$kmlpipe_script_dir/hyperoptic.kml" \
	--google-key =TEST_GOOGLE_KEY > "$kmlpipe_tmpdir/output.kml"
kmlpipe_validate_kml "$kmlpipe_tmpdir/output.kml"
kmlpipe_check_golden_xml "$kmlpipe_script_dir/output.kml" < "$kmlpipe_tmpdir/output.kml"

