#!/bin/bash

source "${BASH_SOURCE%/*}/../../lib/scenario.bash" || exit 1

"$kmlpipe_dir/nestoria/top-keywords" < "$kmlpipe_script_dir/input.kml" | kmlpipe_check_golden "$kmlpipe_script_dir/output.txt"
