#!/bin/bash

source "${BASH_SOURCE%/*}/../../lib/scenario.bash" || exit 1

"$kmlpipe_dir/util/generate-random" --folder-count 3 --places-per-folder 3 --random-seed 42 > "$kmlpipe_tmpdir/output.kml"
kmlpipe_validate_kml "$kmlpipe_tmpdir/output.kml"
kmlpipe_check_golden_xml "$kmlpipe_script_dir/output.kml" < "$kmlpipe_tmpdir/output.kml"
