#!/bin/bash

source "${BASH_SOURCE%/*}/../lib/common.bash" || exit 1

kmlpipe_usage_define <<EOF
For each Link from the selected Link Sets, calculates the great-circle
("as the crow flies") distance between the Places on both sides of the
Link. The result is added to the Link element.

  --link-set-name NAME (required)
    Only process the Link Sets bearing the specified name.
EOF

link_set_name=''
while :
do
	kmlpipe_args_pop_or_error argument
	case "$argument" in
		--link-set-name) kmlpipe_args_pop_or_error link_set_name;;
		--) break;;
		*) kmlpipe_usage_error;;
	esac
done
[[ -n "$link_set_name" ]] || kmlpipe_usage_error
kmlpipe_args_pop_or_error input_file
kmlpipe_args_end

kmlpipe_create_tmpdir

distances_file="$kmlpipe_tmpdir/distances.xml"

kmlpipe_xmlstarlet tr "$kmlpipe_script_dir/link-lnglat.xsl" -s link-set-name="$link_set_name" "$input_file" |
while read -r source_coordinates destination_coordinates
do
	echo "\"$source_coordinates $destination_coordinates \"; lnglat_distance($source_coordinates,$destination_coordinates)"
done |
BC_LINE_LENGTH=0 bc --mathlib "$kmlpipe_dir/lib/lib.bc" |
{
	echo '<?xml version="1.0" encoding="UTF-8"?>'
	echo '<Distances>'
	while read -r source_coordinates destination_coordinates distance_meters
	do
		echo "<Distance source='$source_coordinates' destination='$destination_coordinates' meters='$distance_meters' />"
	done
	echo '</Distances>'
} > "$distances_file"

kmlpipe_xmlstarlet tr "$kmlpipe_script_dir/distance.xsl" -s "distances-file=$distances_file" -s link-set-name="$link_set_name" "$input_file" | kmlpipe_output_xml
