#!/bin/bash

source "${BASH_SOURCE%/*}/../lib/common.bash" || exit 1

output_prefix=''
max_pages=1

kmlpipe_usage_define <<EOF
Fetches property listings from Nestoria, and convert the results to a single KML
folder on standard output. Equivalent to running search-listings-raw,
listings-to-kml, merge-documents and merge-folders.

Any parameters after -- are passed down to search-listings-raw.

Example:

$ search-listings -- \\
	--max-pages 3 -- \\
	--data 'centre_point=51.540,-0.093' --data 'radius=1km' \\
	--data 'listing_type=buy' --data 'price_max=1000000' \\
	--data 'number_of_results=50'
EOF

while :
do
        kmlpipe_args_pop_or_error argument
        case "$argument" in
                --) break;;
                *) kmlpipe_usage_error;;
        esac
done
additional_args=("${kmlpipe_args_stack[@]}")
[[ "${#additional_args[@]}" -gt 0 ]] || kmlpipe_usage_error

kmlpipe_create_tmpdir

"$kmlpipe_script_dir/search-listings-raw" --output-prefix "$kmlpipe_tmpdir/page" "${additional_args[@]}"

for page in "$kmlpipe_tmpdir"/page.*.nestoria-listings.xml
do
	page_number="${page##*/page.}"
	page_number="${page_number%.nestoria-listings.xml}"
	kmlpipe_xmlstarlet tr "$kmlpipe_script_dir/listings-to-kml.xsl" "$page" |
	kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s "new-folder-name=Nestoria Listings Page $page_number" > "$page.kml"
done

"$kmlpipe_dir/util/merge-documents" -- "$kmlpipe_tmpdir"/page.*.nestoria-listings.xml.kml |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/merge-folders.xsl" |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s "new-folder-name=Nestoria Listings" |
kmlpipe_output_xml

