#!/bin/bash

source "${BASH_SOURCE%/*}/../lib/common.bash" || exit 1

output_prefix=''
max_pages=1

kmlpipe_parse_options <<EOF
Fetches property listings from Nestoria, and convert the results to a single KML
document on standard output, with one KML Folder per page. Equivalent to running
search-listings-raw, listings-to-kml and merge.

Any parameters after -- are passed down to search-listings-raw.

Example:

$ search-listings -- \\
	--max-pages 3 -- \\
	--data 'centre_point=51.540,-0.093' --data 'radius=1km' \\
	--data 'listing_type=buy' --data 'price_max=1000000' \\
	--data 'number_of_results=50'
EOF
set -- "${kmlpipe_args[@]}"

while :
do
	arg="$1"
	shift
	case "$arg" in
		'--') break;;
		*) kmlpipe_usage_error "unhandled option: $1";;
	esac
done
additional_args=("$@")

[[ "${#additional_args[@]}" -gt 0 ]] || kmlpipe_usage_error 'must specify arguments for search-listings-raw'

kmlpipe_create_tmpdir

"${BASH_SOURCE%/*}/search-listings-raw" --output-prefix "$kmlpipe_tmpdir/page" "${additional_args[@]}"

for page in "$kmlpipe_tmpdir"/page.*.nestoria-listings.xml
do
	page_number="${page##*/page.}"
	page_number="${page_number%.nestoria-listings.xml}"
	kmlpipe_xmlstarlet tr "${BASH_SOURCE%/*}/listings-to-kml.xsl" "$page" |
	kmlpipe_xmlstarlet tr "${BASH_SOURCE%/*}/../util/rename-folder.xsl" -s "new-folder-name=Nestoria Listings Page $page_number" > "$page.kml" 
done

"${BASH_SOURCE%/*}/../util/merge" "$kmlpipe_tmpdir"/page.*.nestoria-listings.xml.kml |
kmlpipe_output_xml

