#!/bin/bash

source "${BASH_SOURCE%/*}/../lib/common.bash" || exit 1

kmlpipe_usage_define <<EOF
From a KML file containing Nestoria listings, outputs the top Nestoria
keywords that appear in the file, along with its frequency.
EOF

kmlpipe_args_end

kmlpipe_xmlstarlet sel \
	-N 'kml=http://www.opengis.net/kml/2.2' -N 'kmlpipe=http://edechamps.fr/kmlpipe' --template \
		--match '/kml:kml/kml:Document/kml:Folder/kml:Placemark/kmlpipe:Nestoria/listings/@keywords' \
			--value-of '.' --nl |
tr ',' '\n' |
while read -r line
do
	if [[ -n "$line" ]]
	then
		echo "$line"
	fi
done |
sort |
uniq --count |
sort --numeric-sort --key=1 --reverse
