#!/bin/bash

source "${BASH_SOURCE%/*}/../lib/common.bash" || exit 1

sainsburys_file=''
google_key=''

kmlpipe_usage_define <<EOF
Fetches supermarket data for the Edechamps Home Hunt Pipeline.

  --sainsburys_file FILE
    Extract Sainsbury's supermarket locations from JSON file.
    (See sainsburys/README.md for details)

  --google-key KEY (required)
    Google API Key.

EOF

while :
do
	if ! kmlpipe_args_pop argument
	then
		break
	fi
	case "$argument" in
		--sainsburys-file) kmlpipe_args_pop_or_error sainsburys_file;;
		--google-key) kmlpipe_args_pop_or_error google_key;;
		--) break;;
		*) kmlpipe_usage_error;;
	esac
done
[[ -n "$google_key" ]] || kmlpipe_usage_error
kmlpipe_args_end

kmlpipe_create_tmpdir

kmlpipe_jq --raw-output --from-file "$kmlpipe_dir/sainsburys/sainsburys-map.jq" -- "$sainsburys_file" > "$kmlpipe_tmpdir/sainsburys.kml"

# Search for Waitroses in a 10 km radius around London. Filter the Little Waitroses out.
"$kmlpipe_dir/google/place-search" -- --max-pages 5 -- --get --data "key=$google_key" \
	--data 'location=51.540,-0.093' --data 'radius=10000' --data 'keyword=waitrose' \
	'https://maps.googleapis.com/maps/api/place/nearbysearch/xml' |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s 'new-folder-name=Waitrose supermarkets' |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/remove-keyword.xsl" -s 'keyword=Little' > "$kmlpipe_tmpdir/waitrose.kml"

# Search for Tesco Superstores in a 10 km radius around London.
# TODO: Google seems to also return some spurious Tesco Metros in that search.
"$kmlpipe_dir/google/place-search" -- --max-pages 5 -- --get --data "key=$google_key" \
	--data 'location=51.540,-0.093' --data 'radius=10000' --data-urlencode 'keyword="Tesco Superstore"' \
	'https://maps.googleapis.com/maps/api/place/nearbysearch/xml' |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s 'new-folder-name=Tesco supermarkets' > "$kmlpipe_tmpdir/tesco.kml"

"$kmlpipe_dir/util/merge-documents" -- "$kmlpipe_tmpdir/sainsburys.kml" "$kmlpipe_tmpdir/waitrose.kml" "$kmlpipe_tmpdir/tesco.kml" |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/merge-folders.xsl" |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s 'new-folder-name=Supermarkets' |
kmlpipe_output_xml
