#!/bin/bash

source "${BASH_SOURCE%/*}/../lib/common.bash" || exit 1

sainsburys_file=''
google_key=''
manual_file=''
blacklist_file=''
cache_directory=''

kmlpipe_usage_define <<EOF
Fetches supermarket data for the Edechamps Home Hunt Pipeline.

  --sainsburys_file FILE
    Extract Sainsbury's supermarket locations from JSON file.
    (See sainsburys/README.md for details)

  --google-key =KEY (required)
  --google-key @KEYFILE (required)
    Google API Key.

  --manual-supermarkets FILE
    Add supermarkets that appear in the specified file.

  --blacklist-file FILE
    Remove supermarkets that appear in the 'Supermarket Blacklist'
    folder in the specified file.

  --cache-directory DIR
    Reusable cache directory (e.g. for Google searches).

EOF

while :
do
	if ! kmlpipe_args_pop argument
	then
		break
	fi
	case "$argument" in
		--sainsburys-file) kmlpipe_args_pop_or_error sainsburys_file;;
		--google-key) kmlpipe_args_pop_or_error google_key;;
		--manual-file) kmlpipe_args_pop_or_error manual_file;;
		--blacklist-file) kmlpipe_args_pop_or_error blacklist_file;;
		--cache-directory) kmlpipe_args_pop_or_error cache_directory;;
		--) break;;
		*) kmlpipe_usage_error;;
	esac
done
[[ -n "$google_key" ]] || kmlpipe_usage_error
kmlpipe_args_end

kmlpipe_create_tmpdir

kmlpipe_jq --raw-output --from-file "$kmlpipe_dir/sainsburys/sainsburys-map.jq" -- "$sainsburys_file" > "$kmlpipe_tmpdir/sainsburys.kml"

cache() {
	local name="$1"
	shift
	if [[ -z "$cache_directory" ]]
	then
		"$@"
	else
		"$kmlpipe_dir/util/cache" --cache-file "$cache_directory/kmlpipe_edechamps_supermarkets:$name" -- "$@"
	fi
}

# Search for Waitroses in a 10 km radius around London. Filter the Little Waitroses out.
cache waitrose "$kmlpipe_dir/google/place-search" -- --max-pages 5 -- --get --data-urlencode "key$google_key" \
	--data 'location=51.540,-0.093' --data 'radius=10000' --data 'keyword=waitrose' \
	'https://maps.googleapis.com/maps/api/place/nearbysearch/xml' |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s 'new-folder-name=Waitrose supermarkets' |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/remove-keyword.xsl" -s 'keyword=Little' > "$kmlpipe_tmpdir/waitrose.kml"

# Search for Tesco Superstores in a 10 km radius around London.
# TODO: Google seems to also return some spurious Tesco Metros in that search.
cache tesco "$kmlpipe_dir/google/place-search" -- --max-pages 5 -- --get --data-urlencode "key$google_key" \
	--data 'location=51.540,-0.093' --data 'radius=10000' --data-urlencode 'keyword="Tesco Superstore"' \
	'https://maps.googleapis.com/maps/api/place/nearbysearch/xml' |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s 'new-folder-name=Tesco supermarkets' > "$kmlpipe_tmpdir/tesco.kml"

blacklist() {
	if [[ -z "$blacklist_file" ]]
	then
		cat
		return
	fi

	cat > "$kmlpipe_tmpdir/supermarkets.kml"
	"$kmlpipe_dir/util/merge-documents" -- "$kmlpipe_tmpdir/supermarkets.kml" "$blacklist_file" |
	kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/folder-difference.xsl" -s 'remove-from-folder-name=Supermarkets' -s 'compare-against-folder-name=Supermarket Blacklist'
}

merge_documents=("$kmlpipe_tmpdir/sainsburys.kml" "$kmlpipe_tmpdir/waitrose.kml" "$kmlpipe_tmpdir/tesco.kml")
if [[ -n "$manual_file" ]]
then
	merge_documents+=("$manual_file")
fi

"$kmlpipe_dir/util/merge-documents" -- "${merge_documents[@]}" |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/merge-folders.xsl" |
kmlpipe_xmlstarlet tr "$kmlpipe_dir/util/rename-folder.xsl" -s 'new-folder-name=Supermarkets' |
blacklist |
kmlpipe_output_xml
