#!/bin/bash

source "${BASH_SOURCE%/*}/../../lib/scenario.bash" || exit 1

"$kmlpipe_dir/edechamps-home-hunt/get-hyperoptic" --input-zones-file "$kmlpipe_script_dir/zones.kml" --zone-fudge-miles 0.25 < "$kmlpipe_script_dir/input.json" > "$kmlpipe_tmpdir/output.kml"
kmlpipe_validate_kml "$kmlpipe_tmpdir/output.kml"
kmlpipe_check_golden_xml "$kmlpipe_script_dir/output.kml" < "$kmlpipe_tmpdir/output.kml"

